networks:
  sida_network:
    driver: bridge

services:
  poc-ingestion:
    build: ./infra
    image: sida-nodered:latest
    container_name: sida-poc-ingestion
    environment:
      - TZ=America/Recife
      - FLOWS=flows.json
    ports:
      - "1881:1880"
    volumes:
      - ./core/ingestion:/data
      - sida_ipc:/tmp/.ipc
    networks:
      - sida_network
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
  
  poc-context:
    build: ./infra
    image: sida-nodered:latest
    container_name: sida-poc-context
    environment:
      - TZ=America/Recife
      - FLOWS=flows.json
    ports:
      - "1882:1880"
    volumes:
      - ./core/context:/data
      - sida_ipc:/tmp/.ipc
    networks:
      - sida_network
    restart: unless-stopped

  poc-delivery:
    build: ./infra
    image: sida-nodered:latest
    container_name: sida-poc-delivery
    environment:
      - TZ=America/Recife
      - FLOWS=flows.json
    ports:
      - "1883:1880"
    volumes:
      - ./core/delivery:/data
      - sida_ipc:/tmp/.ipc
    networks:
      - sida_network
    restart: unless-stopped

  plc-simulator:
    image: ghcr.io/sida-edge/simulador:latest
    container_name: sida-simulator
    profiles:
      - "sim"
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "5020:5020"
    restart: unless-stopped

volumes:
  sida_ipc: