networks:
  sida_network:
    driver: bridge

services:
  sida-core:
    build: ./sida-core  
    container_name: sida-core
    ports:
      - "8000:8000"
    volumes:
      - ./sida-core/data:/app/data
    networks:
      - sida_network
    restart: unless-stopped

  poc-ingestion:
    build: .
    container_name: sida-poc-ingestion
    environment:
      - TZ=America/Recife
      - FLOWS=flows.json
    ports:
      - "1881:1880"
    volumes:
      - ./core/ingestion:/data
    networks:
      - sida_network
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - sida-core
  
  poc-context:
    image: nodered/node-red:latest
    container_name: sida-poc-context
    environment:
      - TZ=America/Recife
      - FLOWS=flows.json
    ports:
      - "1882:1880"
    volumes:
      - ./core/context:/data
    networks:
      - sida_network
    restart: unless-stopped
    depends_on:
      - sida-core

  poc-delivery:
    image: nodered/node-red:latest
    container_name: sida-poc-delivery
    environment:
      - TZ=America/Recife
      - FLOWS=flows.json
    ports:
      - "1883:1880"
    volumes:
      - ./core/delivery:/data
    networks:
      - sida_network
    restart: unless-stopped
    depends_on:
      - sida-core

  plc-simulator:
    image: ghcr.io/sida-edge/simulador:latest
    container_name: sida-simulator
    profiles:
      - "sim"
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "5020:5020"
    restart: unless-stopped
