networks:
  sida_net:
    driver: bridge

services:
  plc-opcua:
    image: digitalpetri/opc-ua-demo-server:latest
    container_name: sida-sim-opcua
    hostname: localhost
    ports:
      - "12686:12686"
    networks:
      - sida_net
    restart: unless-stopped

  plc-modbus:
    image: tuttas/openplc_v3:latest
    container_name: sida-sim-modbus
    ports:
      - "8080:8080" # Painel Web
      - "502:502"   # Porta Modbus TCP
    networks:
      - sida_net
    restart: unless-stopped

  plc-simulator:
    image: ghcr.io/sida-edge/simulador:latest
    container_name: sida-simulator
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "5020:5020"
    restart: unless-stopped