networks:
  default:
    external: true
    name: sida-edge-net
  
services:
  sida-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sida-worker
    restart: unless-stopped
    depends_on:
      - sida-influxdb
      - sida-memgraph
    environment:
      - MQTT_BROKER_URL=tcp://sida-mosquitto-edge:1883
      - MQTT_CLIENT_ID=sida-worker-edge
      - MQTT_TOPIC=spBv1.0/#
      - INFLUX_TOKEN=token-super-secreto-sida-edge

  sida-influxdb:
    image: influxdb:2.7-alpine
    container_name: sida-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - sida_influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=sida
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token-super-secreto-sida-edge

  sida-memgraph:
    image: memgraph/memgraph-platform
    container_name: sida-memgraph
    restart: unless-stopped
    ports:
      - "7687:7687"
      - "3000:3000"
    volumes:
      - sida_memgraph_data:/var/lib/memgraph

volumes:
  sida_influxdb_data:
  sida_memgraph_data:
