# local
listener 1883
allow_anonymous true

# persistnecia local
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# bridge to cloud
connection bridge_nuvem
address 34.134.241.250:1883

topic spBv1.0/# both 1 "" ""