# local
listener 1883
allow_anonymous true

# persistnecia local
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# bridge to cloud
connection bridge_nuvem
address 136.119.157.112:1883

topic spBv1.0/# both 1 "" ""