# local
listener 1883
allow_anonymous true

# persistnecia local
persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db

autosave_interval 60
max_queued_messages 0 
max_queued_bytes 524288000  # 500 MB

log_dest file /mosquitto/log/mosquitto.log

# bridge to cloud
connection bridge_sida_cloud
address 136.119.157.112:1883
try_private true
cleansession false

topic spBv1.0/# both 1 "" ""
restart_timeout 10